nodeEnv: 'development' # change to production for deployment

uniswap:
  multicallAddress: '0xcA11bde05977b3631167028862bE2a173976CA11'
  ttl: 1000

app:
  name: 'checkout-svc'
  host: 'localhost' # remove for deployment or in docker-compose
  port: 3000
  globalPrefix: 'v1'

log:
  level: 'debug'
  inJson: true

rpc:
  - chainId: 1
    name: 'Ethereum'
    url: 'https://mainnet.infura.io/v3/...'
  - chainId: 5
    name: 'Goerli'
    url: 'https://goerli.infura.io/v3/...'
  - chainId: 137
    name: 'Polygon'
    url: 'https://polygon-mainnet.g.alchemy.com/v2/...'
  - chainId: 43114
    name: 'Avalanche'
    url: 'https://avalanche-mainnet.infura.io/v3/...'
  - chainId: 43113
    name: 'fuji'
    url: 'https://avalanche-fuji.infura.io/v3/...'
  - chainId: 56
    name: 'BSC'
    url: 'https://bsc-mainnet.nodereal.io/v1/...'
  - chainId: 97
    name: 'bsc_testnet'
    url: 'https://bsc-testnet.nodereal.io/v1/...'

dex:
  tokensTTL: 10000
  chainsTTL: 10000

bridge:
  ttl: 10000
